version: '3.9'
services:
  postgresql:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - db:/var/lib/db
    ports:
      - 4000:5432
    networks:
      - jewelry-store
  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_DEFAULT_EMAIL=cmteisrael@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - postgresql
    ports:
      - 5000:80
    networks:
      - jewelry-store
networks:
  jewelry-store:
    driver: bridge
volumes:
  db: {}
