version: '3.9'
services:
  postgresql:
    build: ./db
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - db:/var/lib/db
    ports:
      - 4000:5432
    networks:
      - default
  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_DEFAULT_EMAIL=cmteisrael@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - postgresql
    ports:
      - 5000:80
    networks:
      - default
networks:
  default:
    driver: bridge
volumes:
  db: {}